### ISSUE TITLE
Unknown column DeleteAt

### ISSUE THREAD

**Issue by hamrak** [Sinevia/laravel-cms#10]
After a clean installation according to the instructions, I get an error with a non-existent column after clicking the Translations button.

![Snímka obrazovky 2023-11-13 o 11 26 50](https://github.com/Sinevia/laravel-cms/assets/5807028/3b3e3dd3-0a6c-4160-bf43-a4842a6eca10)

**Comment by lesichkovm** [comment]
The fix is merged and released as [v2.37.0](https://github.com/Sinevia/laravel-cms/releases/tag/v2.37.0) . Thank you @hamrak
