### ISSUE TITLE
Advanced Model does not exists

### ISSUE THREAD

**Issue by Kxtreme** [Sinevia/laravel-cms#2]
on php artisan migrate 
In BaseModel.php line 5:
                                   
  Class 'AdvancedModel' not found  
                                   
the file indeed does not exist.

**Comment by Sinevia** [comment]
Thank you for reporting.

Indeed this step was missing from the README file.

You can install this library with composer:

**composer require lesichkovm/laravel-advanced-model**

The step is now added to the README
