### ISSUE TITLE
vendor publish failure

### ISSUE THREAD

**Issue by baradhili** [Sinevia/laravel-cms#5]
running laravel 5.7 within current homestead environment.
running `php migrate vendor:publish` gives 

```
Copied File [/vendor/sinevia/laravel-cms/config/cms.php] To [/config/cms.php]
Can't locate path: <0>
Can't locate path: <1>
Publishing complete.
```

**Comment by Sinevia** [comment]
Thank you for reporting it. It shoudn''t stop it from being installed.
Its probably related to something similar to: https://stackoverflow.com/questions/42150090/cant-locate-path-0
I will have a coser look

**Comment by lesichkovm** [comment]
This is fixed. Documentation updated with the full list of commands for publishing
