### ISSUE TITLE
error when i wanted to add tranlation

### ISSUE THREAD

**Issue by vhessam** [Sinevia/laravel-cms#7]
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Language' in 'field list' (SQL: insert into `snv_cms_translation_value` (`KeyId`, `Language`, `Value`, `Id`, `UpdatedAt`, `CreatedAt`) values (20201104005855860594, en, , 20201104005855865378, 2020-11-04 00:58:55, 2020-11-04 00:58:55))

**Comment by Sinevia** [comment]
Thank you for reporting it. Looks like a column name was misspelled. 

To quickly fix it rename the Laguage column to Language in the snv_cms_translation_value table.

This is fixed in the new release v2.11.0

**Comment by vhessam** [comment]
many thanks @Sinevia.
I'm gonna update it.

Also it's better to explain that how the translation works.

Many thanks for your package

**Comment by vhessam** [comment]
I mean somewhere in readme

**Comment by Sinevia** [comment]
I see. No worries. I will add an example in the next version.
