### ISSUE TITLE
Widgets

### ISSUE THREAD

**Issue by hariniii98** [Sinevia/laravel-cms#8]
I am trying to add widgets in resources and added types for each widget.. 
Can we add questions or checkboxes for the particular widget?
Also let me know if I can reuse this widget in a page and form in that widget be shown as blank form so that whoever views the page can fill that form?

Please provide any links for documentation if available.

Thank you!

**Comment by Sinevia** [comment]
Hi @hariniii98 thank you for your question

The widgets consist of 2 parts:
parameters:phtml - this is what displays in the CMS admin
and
template.phtml - this is what displays in the frontend

Once you create a widget it will display a code, that you can copy and paste on any page you want it to display

And yes, if your widget is a form (i.e contact form widget) it will display as empty form for each visitor and he will have to fill it in from scratch

**Comment by Sinevia** [comment]
Added as a wiki page at: https://github.com/Sinevia/laravel-cms/wiki/Widgets
